setwd("C:/Users/hcl/Documents/RestaurantData.csv")
RestaurantData<-read.csv("RestaurantData.csv")
print("DATASET")
print(RestaurantData)
print("Type of dataset")
print(class(RestaurantData))
print(mode(RestaurantData))
print(typeof(RestaurantData))

obs=nrow(RestaurantData)
var=ncol(RestaurantData)
print("Number of observations")
print(obs)
print("Number of variables")
print(var)
attach(RestaurantData)
print("Info about rating")
print(summary(RestaurantData$`Number of Ratings`))

